# Based on: https://github.com/actions/starter-workflows/blob/master/ci/node.js.yml

name: global

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

env:
    CI: true
    yarn-cache-name: yarn-cache-3
    yarn-cache-path: .yarn

jobs:
    check-lockfile:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Use or update Yarn cache
              uses: actions/cache@v2
              with:
                  path: ${{ env.yarn-cache-path }}
                  key: ${{ runner.os }}-${{ env.yarn-cache-name }}-${{ hashFiles('**/yarn.lock') }}
            - run: yarn --cache-folder=${{ env.yarn-cache-path }}
            - run: git diff --quiet -- yarn.lock

    format-check:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Use or update Yarn cache
              uses: actions/cache@v2
              with:
                  path: ${{ env.yarn-cache-path }}
                  key: ${{ runner.os }}-${{ env.yarn-cache-name }}-${{ hashFiles('**/yarn.lock') }}
            - run: yarn --cache-folder=${{ env.yarn-cache-path }} --frozen-lockfile
            - run: yarn --cache-folder=${{ env.yarn-cache-path }} format:check

    lint:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Use or update Yarn cache
              uses: actions/cache@v2
              with:
                  path: ${{ env.yarn-cache-path }}
                  key: ${{ runner.os }}-${{ env.yarn-cache-name }}-${{ hashFiles('**/yarn.lock') }}
            - run: yarn --cache-folder=${{ env.yarn-cache-path }} --frozen-lockfile
            - run: yarn --cache-folder=${{ env.yarn-cache-path }} lint

    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Use or update Yarn cache
              uses: actions/cache@v2
              with:
                  path: ${{ env.yarn-cache-path }}
                  key: ${{ runner.os }}-${{ env.yarn-cache-name }}-${{ hashFiles('**/yarn.lock') }}
            - run: yarn --cache-folder=${{ env.yarn-cache-path }} --frozen-lockfile
            - run: yarn --cache-folder=${{ env.yarn-cache-path }} build
            - run: yarn --cache-folder=${{ env.yarn-cache-path }} test

    test-windows:
        runs-on: windows-latest

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Use or update Yarn cache
              uses: actions/cache@v2
              with:
                  path: ${{ env.yarn-cache-path }}
                  key: ${{ runner.os }}-${{ env.yarn-cache-name }}-${{ hashFiles('**/yarn.lock') }}
            - run: yarn --cache-folder=${{ env.yarn-cache-path }} --frozen-lockfile
            - run: yarn --cache-folder=${{ env.yarn-cache-path }} build
            - run: yarn --cache-folder=${{ env.yarn-cache-path }} test
