name: New Portal Release

on:
    schedule:
        # This happens daily
        - cron: '0 0 * * *'

jobs:
    check-for-liferay-release:
        runs-on: ubuntu-latest
        steps:
            - name: Fetch release version
              id: fetch-latest
              run: |
                  curl -sL https://api.github.com/repos/liferay/liferay-portal/releases/latest | \
                  jq -r ".tag_name" | xargs -I {} echo "::set-output name=LATEST_RELEASE::{}"

            - name: Write file
              run: echo "${{ steps.fetch-latest.outputs.LATEST_RELEASE }}" > portal-release.txt

            - name: Cache Latest Portal Release Version
              uses: actions/cache@v2
              id: cache-version
              with:
                  path: ./portal-release.txt
                  key: ${{ steps.fetch-latest.outputs.LATEST_RELEASE }}

            - name: Create Issue
              if: ${{ steps.cache-version.outputs.cache-hit != 'true' }}
              env:
                  TITLE: Update dependencies for Liferay ${{ steps.fetch-latest.outputs.LATEST_RELEASE }}
                  BODY: |
                      Make sure to check the following dependencies to ensure they are updated for latest liferay-portal release.
                      - [ ] Check [Liferay Theme Tasks](https://github.com/liferay/liferay-frontend-projects/blob/master/projects/js-themes-toolkit/packages/liferay-theme-tasks/lib/devDependencies.js#L27)
                      - [ ] Create/Update target-platform for ${{ steps.fetch-latest.outputs.LATEST_RELEASE }}
              run: |
                  curl -X "POST" "https://api.github.com/repos/${{ github.repository }}/issues?state=all" \
                      -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                      -H "Content-Type: text/plain; charset=utf-8" \
                      -d $'{
                        "title": ${{ toJSON(env.TITLE) }},
                        "body": ${{ toJSON(env.BODY) }},
                        "assignees": [],
                        "labels": []
                      }'
